primary:
  driverClassName: com.mysql.cj.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost/gpress_master?characterEncoding=UTF-8&useEncoding=true&autoReconnect=true&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
  username: gpadmin
  password: CRYPT:jhWy/rTtMEt7oGQc7GlWTAZy6mhrXK+FVLh2Hg8v4yY=
  maximumPoolSize: 10
  minimumIdle: 4
  parameters:
    cachePrepStmts: 'true'
secondary:
  driverClassName: com.mysql.cj.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost/gpress_master?characterEncoding=UTF-8&useEncoding=true&autoReconnect=true&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
  username: gpadmin
  password: CRYPT:jhWy/rTtMEt7oGQc7GlWTAZy6mhrXK+FVLh2Hg8v4yY=
  maximumPoolSize: 10
  minimumIdle: 4
  parameters:
    cachePrepStmts: 'true'
