primary:
  driverClassName: com.mysql.cj.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost/gpress_starter?characterEncoding=UTF-8&useEncoding=true&autoReconnect=true&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
  username: ${DATABASE_USE}
  password: ${DATABASE_PWD}
  maximumPoolSize: 10
  minimumIdle: 4
  parameters:
    cachePrepStmts: 'true'
secondary:
  driverClassName: com.mysql.cj.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost/gpress_starter?characterEncoding=UTF-8&useEncoding=true&autoReconnect=true&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
  username: ${DATABASE_USE}
  password: ${DATABASE_PWD}
  maximumPoolSize: 10
  minimumIdle: 4
  parameters:
    cachePrepStmts: 'true'
