primary:
  driverClassName: com.mysql.cj.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost/gpress_starter?characterEncoding=UTF-8&useEncoding=true&autoReconnect=true&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
  username: gpadmin
  password: CRYPT:6770:D16B96D62286D0001BC4F268C501281C
  maximumPoolSize: 10
  minimumIdle: 4
  parameters:
    cachePrepStmts: 'true'
secondary:
  driverClassName: com.mysql.cj.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost/gpress_starter?characterEncoding=UTF-8&useEncoding=true&autoReconnect=true&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
  username: gpadmin
  password: CRYPT:6770:D16B96D62286D0001BC4F268C501281C
  maximumPoolSize: 10
  minimumIdle: 4
  parameters:
    cachePrepStmts: 'true'
